server:
  port: 8081
spring:
  datasource:
    url: ENC(PcEkk/teC6LfHJg5I1pTPmtzEYsaKA8pHwxNf31oaYjmm/0Mg2KBS0lFq4RgGOLENTdpVceg61Ip4st1zY10w36ekTxuF5lRkjOo2iiztassn1CQ2DGXV6U9vEEnMOMC97gsS11RHbemFj/dEx2cxoC7TZ7OclV893w0r2sl0+x897Q4DEUctPy7bMXVJ5tHtXpOtDx3rsscY4qjwMSLKg==)
    username: ENC(PjhsZLjd6Ts3/G3hGl8N2ccYI8Ukr2XBaF1Fx1CcWJsUbp5rBcjqbG75eWb5GUug)
    password: ENC(dmJlc22mzc5t9UfSeFU/1bLJfOegGNO5cvyPrpY6Chj2cKEijkzVFL7APMnGnu3N)
    driver-class-name: ENC(lqg6Gtp+T2wM+/Nc3AG0wEnXELFPrjIEfcjODZ2Xru0O+9gLNF1Xlr/FEcgE4h9Dz5VAqX/76yVytc4sQ9yzcA==)
  data:
    redis:
      host: ENC(aW3mYm0RJTNKum80Lx/qYd1nKpWUWWopxJDbYlM4inUPuN5wassJDrI2yxkbcC0F)
      port: ENC(TtLUElomtCHlxZkUOdiNL0R7hjnS5lp3NDyLRLvYLtHhjw9xBG9wziVR7jB1Txuc)
      database: 1
      password: ENC(GY2o78/H4fjGimUK6b1mN744iQqmH5XwqNxrVPRZhY6cyuBlT6pUySmY/DqHsx8+)
    elasticsearch:
      enable: false
      url: ENC(7PDcewZdpKu5jZdHQv3s5YDzj1Q6iwwhU1JjOSaMq6s6RafvZEDV5/FCPY//rIEveo0D7feTAdLkGu2ISuB02g==)
  cache:
    type: redis
  mail:
    host: ENC(aAZsKTb/SMa017gGXv7hSMi7nFuF6TXok5oniThoMd8jufWMsRVVzS8ru1CWKIdd)
    port: ENC(k+L29uvRR8QPsmKev/yJOpEq5BYKYuYoN9PgHeJFrcvYXmFlYrHLuQvBTX+dvSti)
    protocol: smtps
    default-encoding: UTF-8
    username: ENC(ujH2D3+OMVUO57PY1v9hFwoT4aoI4eF7+Gxvwl6op2irdRN8cMjnpbBfBhB9M6TV)
    password: ENC(t4U0WZmXDCz4JvYJecHr+8PYPsdTM7Qe0ptw93qdjdNwPtR0MTJ5eMiOxXVzI1EBlgGn7akgm3eVN/viUhUUJw==)
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  file:
    name: /app/log/spring.log
  level:
    root: info

token-login:
  encrypt-str-aes-key: ENC(jYesgWmJ5fiqhyn1aqF+ZH5q7tEpAKyu4WhulseEhH3qP00N4SkwHqLVCndg1BryOAP0HZ6QkLVXVYA5/mqcZQ==)

novel:
  local-file-service:
    enable: true
    file-base-path: /app/local-file-service
    url-prefix: /common/image

ali:
  oss:
    access-key-id: ENC(E1/sBrKubV5K9bbxtCBdfunoWqbOYRWPpwaiU9N6BrXhHwSNOJURFKRcAB/zv1J3qWvT5DUxijAIqJDgCK2agA==)
    access-key-secret: ENC(b7i2W3nMkhIpO0c8S0o7eXW9QOtu/uYkpPAizUuPgqFecOBWnkIaaskvVrLBpra4UpxKqpAD8ksyBM8plNnq/w==)
    bucket-name: ENC(Gt/sGS8bS50XxNfDsu2IpSE76WwVcMRC8558azhwKTHErj8FeQtNXJKhXmvt5SEV)
    endpoint: ENC(epxBdyQrbNxhdlGyHZs+4NXxVSw19xvnfVdEDzpoOxhVqyMtsjoMZrKC31V0tiUD7XgGtKXmMeLGbXtjXYTKXRRUywiHbHuLWd54fw/0zPs=)
    url-prefix: /common/image
