server:
  port: 8081
spring:
  datasource:
    url: ENC(MXjtY5vvmU33R3HmQSCL/IBzi7e2neM91vUFj+tOtqPOBluhbtHbAmGgW8DRbXYx3lMNTkFl4pzmVdU6XPUm0NsdTsy97TLjlip9NHgX6n3fx9lvS+sd3OS2+68jy4iBMrXFEYX6Dv8WxlB7upkhow==)
    username: ENC(EcHfbdC4MRth9LtMjnNB7pOltZlWDVOPNLiAr6XdD1l6YGzWWGZ5upKfkc3hT3pl)
    password: ENC(pqJVCPDG1n2T2FXGqDDhqk1QBUiPNPy77TW0wvTdhkfSc0aS1jjCrecP//ma183w)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ENC(cEA1QZGdeLqlm5oel6dqMuS1s8md/ZKEmWUt18D+MQFHqCDTuPuE/DKvrSIFfA5s)
      port: ENC(GJXOs5vNnTLyqlDChOEX4WZBnjTiwNXQDXrssG1ZZIIsUHIZtnVUGn6ZwNKY0p99)
      database: ENC(uU70zSXYXt4qdpBotlkXZ2DfFz1hQBR0FJygc2UMZyvWahxObkmxAXmpYjH4OK+S)
      password: ENC(krFMtNi1TpX87UkUiBjrhN5iGJEg71cDFAdigRh7WZCLPFZ7vdQVsODwC+xP5jvb)
    elasticsearch:
      url: ENC(7PDcewZdpKu5jZdHQv3s5YDzj1Q6iwwhU1JjOSaMq6s6RafvZEDV5/FCPY//rIEveo0D7feTAdLkGu2ISuB02g==)
  cache:
    type: redis
  mail:
    host: ENC(aAZsKTb/SMa017gGXv7hSMi7nFuF6TXok5oniThoMd8jufWMsRVVzS8ru1CWKIdd)
    port: ENC(k+L29uvRR8QPsmKev/yJOpEq5BYKYuYoN9PgHeJFrcvYXmFlYrHLuQvBTX+dvSti)
    protocol: smtps
    default-encoding: UTF-8
    username: ENC(ujH2D3+OMVUO57PY1v9hFwoT4aoI4eF7+Gxvwl6op2irdRN8cMjnpbBfBhB9M6TV)
    password: ENC(t4U0WZmXDCz4JvYJecHr+8PYPsdTM7Qe0ptw93qdjdNwPtR0MTJ5eMiOxXVzI1EBlgGn7akgm3eVN/viUhUUJw==)
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  file:
    name: /novel-backend/log/spring.log
  level:
    root: info

token-login:
  encrypt-str-aes-key: ENC(jYesgWmJ5fiqhyn1aqF+ZH5q7tEpAKyu4WhulseEhH3qP00N4SkwHqLVCndg1BryOAP0HZ6QkLVXVYA5/mqcZQ==)

novel:
  local-file-service:
    file-base-path: /novel-backend/local-file-service
    url-prefix: /common/image

ali:
  oss:
    enable: true
    access-key-id: ENC(E1/sBrKubV5K9bbxtCBdfunoWqbOYRWPpwaiU9N6BrXhHwSNOJURFKRcAB/zv1J3qWvT5DUxijAIqJDgCK2agA==)
    access-key-secret: ENC(b7i2W3nMkhIpO0c8S0o7eXW9QOtu/uYkpPAizUuPgqFecOBWnkIaaskvVrLBpra4UpxKqpAD8ksyBM8plNnq/w==)
    bucket-name: ENC(Gt/sGS8bS50XxNfDsu2IpSE76WwVcMRC8558azhwKTHErj8FeQtNXJKhXmvt5SEV)
    endpoint: ENC(epxBdyQrbNxhdlGyHZs+4NXxVSw19xvnfVdEDzpoOxhVqyMtsjoMZrKC31V0tiUD7XgGtKXmMeLGbXtjXYTKXRRUywiHbHuLWd54fw/0zPs=)
    url-prefix: /common/image
