spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 6MB
novel:
  ttl:
    captcha-ttl-seconds: 300
token-login:
  jwt-ttl-seconds: 259200 # 3天
  jwt-refresh-ttl-seconds: 86400 # 1天
  exclude-patterns:
    - /error
    - /doc.html/**
    - /swagger-ui.html/**
    - /v3/api-docs/**
    - /user/login
    - /user/signup
    - /user/forget-password
    - /common/captcha
    - /common/verify-email
    - /common/image/**
    - /common/public-key
    - /novel/carousel
    - /novel/ranklist
    - /novel/recommend
    - /novel/related
    - /novel/hot
    - /novel/available-tags
    - /novel/get-by-tags
    - /novel/hot-tags
    - /novel/chapter
    - /novel/chapter/previous
    - /novel/chapter/next
    - /novel/contents
    - /novel
    - /novel/comment
