spring:
  profiles:
    active: dev
novel:
  ttl:
    captcha-ttl-seconds: 300
token-login:
  jwt-ttl-seconds: 600
  exclude-patterns:
    - /error
    - /doc.html/**
    - /swagger-ui.html/**
    - /v3/api-docs/**
    - /user/login
    - /user/signup
    - /common/captcha