spring:
  datasource:
    url: jdbc:mysql://localhost:3306/novel_backend?rewriteBatchedStatements=true
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
    elasticsearch:
      enable: false
      url: http://localhost:9200
  cache:
    type: redis
  mail:
    host: 
    port: 
    protocol: 
    default-encoding: 
    username: 
    password: 
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.abdecd.novelbackend.business.controller

token-login:
  encrypt-str-aes-key: 
  test: true

novel:
  local-file-service:
    enable: true
    file-base-path: 
    url-prefix: /common/image

ali:
  oss:
    access-key-id: 
    access-key-secret: 
    bucket-name: 
    endpoint: 
    url-prefix: /common/image
