spring:
  profiles:
    active: dev
novel:
  ttl:
    captcha-ttl-seconds: 300
token-login:
  jwt-ttl-seconds: 259200 # 3天
  exclude-patterns:
    - /error
    - /doc.html/**
    - /swagger-ui.html/**
    - /v3/api-docs/**
    - /user/login
    - /user/signup
    - /user/forget-password
    - /common/captcha
    - /common/verify-email
    - /common/image/**
    - /common/public-key
    - /novel/carousel
    - /novel/ranklist
    - /novel/recommend
    - /novel/related
