name: Deploy to Server
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'

    - name: Setup SSH Keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Build with Maven
      run: mvn clean package -Pprod -DskipTests=true

    - name: Get JAR base name and timestamp
      id: jar_info
      run: |
        JAR_FILE_WITH_SUFFIX=$(find business/target -type f -name "*.jar")
        JAR_BASE_NAME=$(basename "$JAR_FILE_WITH_SUFFIX" .jar)
        JAR_TIMESTAMP=$(date +%Y%m%d%H%M%S)
        echo "JAR_BASE_NAME=$JAR_BASE_NAME" >> $GITHUB_ENV
        echo "TIMESTAMP=$JAR_TIMESTAMP" >> $GITHUB_ENV

    - name: Copy to Server and Run
      run: |
        cd business/target
        ssh ${{ secrets.USER_NAME }}@${{ secrets.SERVER_IP }} 'mkdir -p ~/novel-backend'
        scp ${{ env.JAR_BASE_NAME }}.jar ${{ secrets.USER_NAME }}@${{ secrets.SERVER_IP }}:~/novel-backend/${{ env.JAR_BASE_NAME }}.jar
        ssh ${{ secrets.USER_NAME }}@${{ secrets.SERVER_IP }} '
          screen -S novel-backend -X quit
          sleep 10
          screen -dmS novel-backend
          screen -S novel-backend -X stuff "cd ~/novel-backend; java -jar ${{ env.JAR_BASE_NAME }}.jar --spring.profiles.active=prod$(printf \\r)"
        '
